language: cpp
dist: trusty

before_install:
  - git submodule init
  - git submodule update
  - ./configure.sh

install:
  - sudo apt-get update
  - sudo apt-get install -y valgrind

compiler:
  - gcc
  - clang

script:
  - ./test.sh

notifications:
  email:
    on_success: never
    on_failure: never