language: cpp
compiler: gcc
dist: trusty

before_install:
  - git submodule init
  - git submodule update
  - ./configure

script:
  - ./test

notifications:
  email:
    on_success: never
    on_failure: never